spring:
  application:
    name: paymentsystem
  config:
    import: optional:application-local.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

payment:
  imp-code: ${IMP_CODE}
  imp-key: ${IMP_KEY}
  imp-secret: ${IMP_SECRET}
  user-email: ${USER_EMAIL}
  user-name: ${USER_NAME}

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}
