spring.application.name=paymentsystem
spring.config.import=optional:application-local.properties

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

payment.imp-code=${IMP_CODE}
payment.imp-key=${IMP_KEY}
payment.imp-secret=${IMP_SECRET}

slack.webhook.url=${SLACK_WEBHOOK_URL}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.listener.simple.default-requeue-rejected=false
